# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Lucas Vieira

description: >- # this means to ignore newlines until "baseurl:"
  by Lucas Santos
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://iamlucassantos.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
author:
  name: Lucas Vieira
  email: "lucas6eng@gmail.com"
  github: "https://github.com/iamlucasvieira"
  linkedin: "https://www.linkedin.com/in/iamlucasvieira/"
  resume: "download/Lucas-CV.pdf"

# Build settings
# theme: minima

plugins:
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: jekyll/minima@master

minima:
  skin: solarized-dark
  # social_links:
  #   github: iamlucassantos
  #   linkedin: lucasvsantosd
  #   twitter: lucas6eng

# defaults:
#   - scope:
#       path: "assets/images"
#     values:
#       image: true
# defaults:
#   -
#     scope:
#       path: "/:categories/:title"
#       type: "post"
#     values:
#       layout: "post"
#       permalink: "/:categories/:title"
#       author: "Lucas Santos"
#       comments: True

      # Values
header_pages:
  - home.md
  - about.md
  - projects.md
  - posts.md

# disqus:
#   shortname: iamlucassantos

sass:
    sass_dir: _sass

collections:
  projects:
    permalink: /:collection/:title
    output: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
